server:
  port: 8081

spring:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  sercetkey: sssssss

openapi:
  service:
    title: Backend API Document
    version: v1.1.0
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
